version: '3.8'

services:

  hackathon-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  hackathon-api:
    image: lucasgoleiro/hackathon-api
    ports:
      - 8080:8080
    depends_on:
      - hackathon-db